# Generated by Django 4.1.5 on 2023-01-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_title', models.CharField(help_text='Введите название работы', max_length=256, verbose_name='Название работы')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в БД')),
                ('material_type', models.CharField(choices=[('kr', 'Курсовая работа'), ('dr', 'Дипломная работа'), ('pr', 'Практическая работа'), ('lr', 'Лабораторная работа')], help_text='Выберите соответсующий тип работы', max_length=32, verbose_name='Тип работы')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(help_text='Введите название дисциплины', max_length=256, verbose_name='Название дисциплины')),
            ],
            options={
                'ordering': ['subject_title'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('git', models.URLField(blank=True, verbose_name='Ссылка на github')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Ваш емэйл')),
                ('photo', models.ImageField(upload_to='team', verbose_name='Фотография')),
                ('posn', models.CharField(choices=[('DS', 'Design'), ('FD', 'Frontend Developer'), ('BD', 'Backend Developer'), ('PM', 'Project Manager'), ('TT', 'Tester')], max_length=128, verbose_name='Роль в команде')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(help_text='Введите цитату', verbose_name='Цитата')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_samgtudist.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ManyToManyField(related_name='materials_related', related_query_name='material', to='api_samgtudist.subject'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('docx', 'Word'), ('doc', 'Word old'), ('pdf', 'PDF'), ('jpeg', 'Pictures'), ('xls', 'Excel')], max_length=10)),
                ('file', models.FileField(upload_to='works')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_samgtudist.material')),
            ],
        ),
        migrations.CreateModel(
            name='ExamplePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField(help_text='Сохраняется сгенерированный HTML текст для отображения на сайте', verbose_name='HTML текст')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_samgtudist.material')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(help_text='Введите содержание работы', verbose_name='Содержание')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_samgtudist.material')),
            ],
        ),
    ]
