# Generated by Django 4.1.5 on 2023-01-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_samgtudist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Содержание', 'verbose_name_plural': 'Содержания'},
        ),
        migrations.AlterModelOptions(
            name='examplepage',
            options={'verbose_name': 'Пример Страницы', 'verbose_name_plural': 'Примеры Страниц'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_title'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['last_name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AlterField(
            model_name='content',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_text', to='api_samgtudist.material'),
        ),
        migrations.AlterField(
            model_name='examplepage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_page', to='api_samgtudist.material'),
        ),
        migrations.AlterField(
            model_name='examplepage',
            name='page',
            field=models.TextField(help_text='Сохраняется сгенерированный HTML текст для сайта', verbose_name='HTML текст'),
        ),
        migrations.AlterField(
            model_name='file',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_with_work', to='api_samgtudist.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('kr', 'Курсовая работа'), ('dr', 'Дипломная работа'), ('pr', 'Практическая работа'), ('lr', 'Лабораторная работа'), ('exam', 'Экзамен'), ('ex_anw', 'Ответы на вопросы для экамена'), ('dl', 'Доклад'), ('pos', 'Методические пособие'), ('task', 'Задача')], help_text='Выберите соответсующий тип работы', max_length=32, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', related_query_name='quotes_set', to='api_samgtudist.material'),
        ),
    ]
