# Generated by Django 4.1.5 on 2023-01-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_samgtudist",
            "0002_alter_content_options_alter_examplepage_options_and_more",
        )
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image", verbose_name="Иллюстрации к работе"
                    ),
                ),
            ],
        ),
        migrations.RenameModel(old_name="Quote", new_name="Paragraph"),
        migrations.RemoveField(model_name="examplepage", name="material"),
        migrations.AlterModelOptions(
            name="paragraph",
            options={"verbose_name": "Абзац", "verbose_name_plural": "Абзацы"},
        ),
        migrations.RenameField(
            model_name="paragraph", old_name="quote_text", new_name="paragraph_text"
        ),
        migrations.AlterField(
            model_name="material",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("kr", "Курсовая работа"),
                    ("dr", "Дипломная работа"),
                    ("pr", "Практическая работа"),
                    ("lr", "Лабораторная работа"),
                    ("rgr", "Расчетно-графическая работа"),
                    ("pz", "Пояснительная записка"),
                    ("upp", "Учебная/Производственная практика"),
                    ("vkr", "Выпускная квалификационная работа"),
                    ("test", "Тест"),
                    ("chert", "Чертеж"),
                    ("eskiz", "Эскиз"),
                    ("maket", "Макет"),
                    ("lkc", "Лекция"),
                    ("tr", "Типовой расчет"),
                    ("esse", "Эссе"),
                    ("exam", "Экзамен"),
                    ("ex_anw", "Ответы на вопросы для экамена"),
                    ("ans_test", "Ответы к тесту"),
                    ("dl", "Доклад"),
                    ("rt", "Рабочая Тетрадь"),
                    ("ref", "Реферат"),
                    ("pos", "Методические пособие"),
                    ("task", "Задача"),
                    ("var", "Другое"),
                ],
                help_text="Выберите соответсующий тип работы",
                max_length=32,
                verbose_name="Тип работы",
            ),
        ),
        migrations.DeleteModel(name="Content"),
        migrations.DeleteModel(name="ExamplePage"),
        migrations.AddField(
            model_name="picture",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api_samgtudist.material",
            ),
        ),
    ]
